---
include:
  - board: eyelash_corne_left
    shield: nice_view_adapter nice_shield_spacemarine

  - board: eyelash_corne_right
    shield: nice_view_adapter nice_shield_spacemarine

  - board: eyelash_corne_left
    shield: nice_view_adapter nice_shield_spacemarine
    snippet: studio-rpc-usb-uart
    cmake-args: -DCONFIG_ZMK_STUDIO=y
    artifact-name: eyelash_corne_studio_left

  - board: eyelash_corne_left
    shield: settings_reset
