---
include:
  # Normal firmware (both halves) with Space Marine status screen
  - board: eyelash_corne_left
    shield: nice_view_gem nice_shield_spacemarine
    #snippet: zmk-usb-logging    # Uncomment to log over USB

  - board: eyelash_corne_right
    shield: nice_view_gem nice_shield_spacemarine
    #snippet: zmk-usb-logging    # Uncomment to log over USB

  # ZMK Studio build (left half) with Space Marine screen
  - board: eyelash_corne_left
    shield: nice_view_gem nice_shield_spacemarine
    snippet: studio-rpc-usb-uart
    cmake-args: -DCONFIG_ZMK_STUDIO=y
    artifact-name: eyelash_corne_studio_left

  # Settings reset UF2 (left half)
  - board: eyelash_corne_left
    shield: settings_reset
    #snippet: zmk-usb-logging
